name: Setup Minecraft

on:
  push:
    branches:
      - main

jobs:
  setup-minecraft:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Minecraft
      id: minecraft
      uses: mcenv/setup-minecraft@v3
      with:
        version: "1.12.2"

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: "microsoft"
        java-version: ${{ fromJson(steps.minecraft.outputs.package).javaVersion.majorVersion }}

    - name: Run Minecraft
      run: |
        echo "Running Minecraft ${{ steps.minecraft.outputs.version }}."
        echo "eula=true" > eula.txt
        java -jar $MINECRAFT nogui
